steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/intense-reason-435618-j2/resumeui', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/intense-reason-435618-j2/resumeui']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
      - gcloud run deploy resume-ui-service \
        --image gcr.io/intense-reason-435618-j2/resumeui \
        --platform managed \ 
        --region us-central1 \
        --allow-unauthenticated
  
options:
  logging: CLOUD_LOGGING_ONLY